### PR TITLE
Mission system

### LINKED ISSUE #419: Shovel, croptile, terraintile interaction bug
## Description
Shovel behaviour not working as intended.

## How To Reproduce
Steps to reproduce the behaviour:
1. Create Croptile
2. Plant seed in Croptile
3. Use shovel on Croptile
4. See error - the texture of croptile becomes un-interactable, another croptile can be created on top of it, croptile cannot be destroyed.

## Expected Behaviour
CropTile should be able to be interacted with, even after shovelling a croptile with a plant on it.

## Temporary Fix
Do not shovel a croptile that has a plant on it.

### PR DESCRIPTION
**Pull request by DonghyugDavidJeong**
Adds initial storyline, decreases water level reduction rate by 10 times, adds system for rewarding quests, and fixes #419.

### CODE REVIEW

**Review by charliebkw — APPROVED** [review]
Looks good

**Review by lucashicks1 — APPROVED** [review]
LGTM

**Review by shristigupta1408 — APPROVED** [review]

**Review by Tom-Strooper — APPROVED** [review]
Changes look good, but we should probably get a few ppl from other teams to check off before merge.

**Review by Tom-Strooper — APPROVED** [review]
Made some changes to remove unnecessary methods in Quest, and removed 2 example quests from MissionManager constructor. I think this looks better now

File: source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java [hunk 1]
```diff
@@ -215,7 +216,7 @@ public float getWaterContent() {
 	 *
 	 * @return whether the tile is occupied by the plant
 	 */
-	private boolean isOccupied() {
+	public boolean isOccupied() {
```
Comment (vilnor) [inline source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java:219]: Was this meant to be changed to public?

**Review by vilnor — APPROVED** [review]
Looks good! 

Just left one very minor comment, not too fussed about it.

File: source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java (hunk 1 above)
Comment (DonghyugDavidJeong) [reply source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java:219]: Yeah, I think we wanted to have it public to begin with for interaction with plant but handled it differently so it worked with it being private. I changed it to public again because of the bug outlined in #419, and the easiest fix was to know if the cropTile had something on it.

Comment (vilnor) [reply source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java:219]: I can't see it being used outside of `CropTileComponent` anymore in this pr but no worries. 

I've got a different fix in my branch that works with the recent changes Jackson merged into main, I'm happy to just change it back to private there.

Comment (DonghyugDavidJeong) [reply source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java:219]: Sure, that would be great. I honestly didn't bother checking through all the uses of isOccupied that changed while merging (too many conflicts), and also because apparently itemActions and tile interactions are changing again.

Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/areas/terrain/CropTileComponent.java:219]: This was requested for an earlier change to the way tiles interact, but I think team 1 plans on changing tile/terrain interaction again.
