### PR TITLE
Fix item consumable checking

### LINKED ISSUE #523: Removing seeds does not work
## Description
When placing a seed on a plant / seedling / seed (any plant on a croptile) the seed is consumed but not actually used to plant anything. This locks you out of the entire game if done in the tutorial.

## How To Reproduce
Steps to reproduce the behaviour:
1. Get 2 seeds
2. Hoe the ground
3. Plant one on the tilled ground
4. Plant one on top of the other

## Expected Behaviour
One seed is consumed and the other is not.

## Additional Context
This can force the player to reset as they would be left without seeds and thus needs to be fixed

## Temporary Fix
Do not plant a seed on another plant

### PR DESCRIPTION
**Pull request by Tom-Strooper**
Fixes #523, although the current solution does not integrate with the `perishable` boolean logic.
(This could be updated in sprint 4 so the two implementations work together).

### CODE REVIEW

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java [hunk 1]
```diff
@@ -308,9 +308,12 @@ private boolean hoe(Vector2 playerPos, Vector2 mousePos) {
    */
   private boolean fertilise(TerrainTile tile) {
     if (isCropTile(tile.getOccupant())) {
+      CropTileComponent cropTileComponent = tile.getOccupant().getComponent(CropTileComponent.class);
+      if (cropTileComponent != null && !cropTileComponent.isFertilised()) {
```
Comment (JTrenerry) [inline source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: if cropTile is null this will be like NoneType has no isFertilised() method

Comment (JTrenerry) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: but isCropTile() checks that so wont actually happen just checked twice ig

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java [hunk 2]
```diff
@@ -324,10 +327,13 @@ private boolean fertilise(TerrainTile tile) {
    */
   private boolean plant(TerrainTile tile) {
     if (isCropTile(tile.getOccupant())) {
+      CropTileComponent cropTileComponent = tile.getOccupant().getComponent(CropTileComponent.class);
+      if (cropTileComponent != null && cropTileComponent.getPlant() == null) {
+        // Planting using seeds should remove the item from player inventory
```
Comment (JTrenerry) [inline source/core/src/main/com/csse3200/game/components/items/ItemActions.java:332]: same here, also would want to move the other code inside the if so you get correct bool return and you dont trigger an event that will do nothing

**Review by JTrenerry — CHANGES_REQUESTED** [review]
added comments

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 1 above)
Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: That's why I check that it's not null in the previous condition of the && statement

Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: It shortcircuits if cropTileComponent is null

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 2 above)
Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:332]: Same here

Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:332]: I can't move it to the other side cause if it is a croptilecomponent and the plant/fertilize method is called, cause then getPlant will always return an entity. We need to check that before we plant something on the tile or fertilise the tile that the tile does not have a plant or the tile is not fertilised

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 1 above)
Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: also isCropTile is also checked immediately beforehand

Comment (JTrenerry) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: cropTile checks if it has a CropTileComp so the first half of ur if is useless, and and if statement checks both sides before returning so would still break

**Comment by Tom-Strooper** [comment]
> added comments

I'll make it call the plant and fertilize methods inside the if. The other note about cropTileComponent maybe being null is already dealt with

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 2 above)
Comment (JTrenerry) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:332]: I dont understand, just bring up triggering the plant event after it checks that there is no plant and not regardless of a plant being there or not?

**Review by DonghyugDavidJeong — APPROVED** [review]
works on my machine

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 1 above)
Comment (lucashicks1) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:312]: Would the second if statement not just short circuit? If the component was null, the first condition would evaluate to `false` then it wouldn't bother evaluating `!cropTileComponent.isFertilised()`

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 2 above)
Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java:332]: ye sorry I misunderstood what u meant but I've updated the comment and code now

**Comment by JTrenerry** [comment]
> > added comments
> 
> I'll make it call the plant and fertilize methods inside the if. The other note about cropTileComponent maybe being null is already dealt with

its dealt with twice though, which is not needed

File: source/core/src/main/com/csse3200/game/components/items/ItemActions.java (hunk 1 above)
Comment (Tom-Strooper) [reply source/core/src/main/com/csse3200/game/components/items/ItemActions.java]: I've removed the double-check for cropTileComponent being not null, but && is shortcircuit so it wouldn't

**Comment by Tom-Strooper** [comment]
> > > added comments
> > 
> > 
> > I'll make it call the plant and fertilize methods inside the if. The other note about cropTileComponent maybe being null is already dealt with
> 
> its dealt with twice though, which is not needed

ye I've updated in most recent change

**Comment by JTrenerry** [comment]
> > > > added comments
> > > 
> > > 
> > > I'll make it call the plant and fertilize methods inside the if. The other note about cropTileComponent maybe being null is already dealt with
> > 
> > 
> > its dealt with twice though, which is not needed
> 
> ye I've updated in most recent change

ah i c ty

**Review by lucashicks1 — APPROVED** [review]
Works on my machine

**Review by JTrenerry — APPROVED** [review]
