### PR TITLE
#350 Implemented `ShipPartTileComponent`

### LINKED ISSUE #419: Shovel, croptile, terraintile interaction bug
## Description
Shovel behaviour not working as intended.

## How To Reproduce
Steps to reproduce the behaviour:
1. Create Croptile
2. Plant seed in Croptile
3. Use shovel on Croptile
4. See error - the texture of croptile becomes un-interactable, another croptile can be created on top of it, croptile cannot be destroyed.

## Expected Behaviour
CropTile should be able to be interacted with, even after shovelling a croptile with a plant on it.

## Temporary Fix
Do not shovel a croptile that has a plant on it.

### PR DESCRIPTION
**Pull request by vilnor**
* Added a Ship Part Tile that can hold a Ship Debris
* Ship Debris must be destroyed first before the Ship Part Tile can be destroyed
* Added a terrain tile to "destroy" events - fixes #419 

- the tile currently drops an egg, this will get updated once the Ship Part Item is implemented

### CODE REVIEW

File: source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+     *             tile is destroyed.
+     */
+    private void destroyTile(TerrainTile tile) {
+        if (containsShipDebris()) {
+            destroyShipDebris();
+        } else {
+            // drop a ship part
+            Entity item = ItemFactory.createEgg(); // the ship is made of eggs apparently
+            item.setPosition(entity.getPosition());
+            ServiceLocator.getEntityService().register(item);
```
Comment (JTrenerry) [inline source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java:67]: does this work? might be better to call spawnEntityAt() or spawnEntity, same output but better :p

**Review by JTrenerry — COMMENTED** [review]
Added a comment

File: source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java (hunk 1 above)
Comment (vilnor) [reply source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java:67]: yeah it does, I followed how we spawn items in other places.

idk if spawnEntityAt is cleaner, coz then we gotta convert from the player entity position to a map tile coordinate.

Comment (JTrenerry) [reply source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java:67]: hm, I dislike how we spawn it for peaceable destruction so was gonna change that, and there is a function in the GameMap that can convert, but it maybe just easier that way, just checking cause I don't wanna walk to pc, does spawn entity do anything else?

Comment (vilnor) [reply source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java:67]: spawnEntity does the same as spawnEntityAt just without setting the position

Comment (vilnor) [reply source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java:67]: it just feels a little silly to be converting from entity world pos -> tile pos -> world pos again in spawnEntityAt

Comment (JTrenerry) [reply source/core/src/main/com/csse3200/game/areas/terrain/ShipPartTileComponent.java:67]: don't look at the code to hoe then lmaooo, but yeah I mean it looks fine with me and as long as it works, it works.

**Review by DonghyugDavidJeong — APPROVED** [review]
New code makes sense to me, but I only looked at the CropTile related stuff cos idk the decisions made on the ship parts.

**Review by JTrenerry — APPROVED** [review]

**Review by bunnyycat — APPROVED** [review]
approved!
